In [1]:
##Q4:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [2]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [3]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.shape(num_list)

(2, 3)

In [5]:
np.size(num_list, axis = 1)

3

In [7]:
np.shape(num_array)

(2, 3)

In [9]:
np.size(num_array, axis = 0)

2

In [14]:
arr1 = np.random.randint(1,10, (3,4))

In [15]:
arr1

array([[1, 2, 8, 1],
       [8, 5, 5, 9],
       [6, 3, 6, 7]])

In [36]:
arr2 = np.zeros((1, 3,3))

In [37]:
arr2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [40]:
np.shape(arr2)

(1, 3, 3)

In [39]:
np.size(arr2)

9

In [41]:
##Q6:
dimension = int(input("Enter the dimension of identitiy matrix: "))
identity_matrix = np.identity(dimension, dtype="int")
print(identity_matrix)

Enter the dimension of identitiy matrix: 5
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [43]:
np.shape(identity_matrix)

(5, 5)

In [44]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
##Q3:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)

In [57]:
type(list_)

list

In [58]:
array_list

array([1, 2, 3, 4, 5])

In [59]:
type(array_list)

numpy.ndarray

In [60]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [61]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [63]:
##Q1:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [64]:
type(list_)

list

In [65]:
type(array_list)

numpy.ndarray

In [66]:
##Q2:

for  i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [67]:
for  i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
